# **Actividad 4.1 (Regresión Logística)**

## Carga y preprocesamiento de datos

In [24]:
import pandas as pd
import numpy as np
from scipy.optimize import curve_fit
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
df=pd.read_csv("Rio_limpio.csv", index_col=0)
df.head()

source                                   name  host_since  \
0  city scrape      Unbelievable Ocean View Apartment  2011-11-19   
1  city scrape    EXCELENTE APARTAMENTO EM COPACABANA  2013-07-15   
2  city scrape                  Comfort em Copacabana  2011-11-20   
3  city scrape       Amazing Huge Apartment in Leblon  2011-04-25   
4  city scrape  Lindo quarto sossegado para temporada  2011-05-04   

            host_location  host_response_time host_is_superhost  \
0  Rio de Janeiro, Brazil  a few days or more                 f   
1  Rio de Janeiro, Brazil        Sin registro                 f   
2  Rio de Janeiro, Brazil      within an hour                 t   
3  Rio de Janeiro, Brazil        Sin registro                 f   
4  Rio de Janeiro, Brazil  within a few hours                 f   

  host_neighbourhood host_identity_verified           neighbourhood  \
0            Vidigal                      t  Rio de Janeiro, Brazil   
1       Sin registro                      f  Rio de Janeiro, Brazil   
2         Copacabana                      t            Sin registro   
3             Leblon                      f            Sin registro   
4       Santa Teresa                      t  Rio de Janeiro, Brazil   

  neighbourhood_cleansed  ... review_scores_cleanliness review_scores_checkin  \
0                Vidigal  ...                      4.90                  4.90   
1             Copacabana  ...                      4.87                  4.97   
2             Copacabana  ...                      4.94                  4.94   
3                 Leblon  ...                      4.80                  4.90   
4           Santa Teresa  ...                      5.00                  5.00   

  review_scores_communication review_scores_location review_scores_value  \
0                        4.90                   4.90                4.80   
1                        4.97                   4.97                4.86   
2                        5.00                   4.97                4.94   
3                        4.90                   4.90                4.70   
4                        5.00                   4.90                4.80   

  calculated_host_listings_count  calculated_host_listings_count_entire_homes  \
0                            1.0                                          1.0   
1                            2.0                                          2.0   
2                            5.0                                          3.0   
3                            1.0                                          1.0   
4                            5.0                                          0.0   

   calculated_host_listings_count_private_rooms  \
0                                           0.0   
1                                           0.0   
2                                           2.0   
3                                           0.0   
4                                           0.3   

   calculated_host_listings_count_shared_rooms  reviews_per_month  
0                                          0.0               0.05  
1                                          0.0               2.31  
2                                          0.0               0.25  
3                                          0.0               1.20  
4                                          0.0               0.04  

[5 rows x 50 columns]

In [25]:
df = df[df['host_is_superhost'] != 'Sin registro']
df = df[df['host_identity_verified'] != 'Sin registro']
df = df[df['has_availability'] != 'Sin registro']
df = df[df['instant_bookable'] != 'Sin registro']

print(df["instant_bookable"].value_counts())



instant_bookable
f    29211
t     8626
Name: count, dtype: int64


## Analizar 10 casos de correlación logística que existe entre diferentes variables de nuestra base de datos, aplicando la herramienta de **“Regresión Logística”**

### host_is_superhost

In [26]:
Vars_Indep=df[["price", "beds", "review_scores_cleanliness", "bathrooms", "review_scores_value", "review_scores_location", "reviews_per_month"]]
Var_dep=df["host_is_superhost"]

X=Vars_Indep
y=Var_dep

#Dividir el conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

#Escalar los datos
escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)

#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión:")
print(matriz)
print("\n")

#Calcular la precisión
from sklearn.metrics import precision_score
precision1=precision_score(y_test, y_pred, average="binary", pos_label="t")
precision2=precision_score(y_test, y_pred, average="binary", pos_label="f")

#Calcular la exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)

#Calcular la sensibilidad
from sklearn.metrics import recall_score
sensibilidad1=recall_score(y_test, y_pred, average="binary", pos_label="t")
sensibilidad2=recall_score(y_test, y_pred, average="binary", pos_label="f")

print("Precision del modelo t:")
print(precision1)
print("Precision del modelo f:")
print(precision2)
print("\n")
print("Exactitud del modelo:")
print(exactitud)
print("\n")
print("Sensibilidad del modelo t:")
print(sensibilidad1)
print("Sensibilidad del modelo f:")
print(sensibilidad2)

Matriz de confusión:
[[7350  371]
 [2914  717]]


Precision del modelo t:
0.6590073529411765
Precision del modelo f:
0.7160950896336711


Exactitud del modelo:
0.7106236786469344


Sensibilidad del modelo t:
0.19746626273753787
Sensibilidad del modelo f:
0.9519492293744334


### host_identity_verified

In [27]:
Vars_Indep=df[["price", "beds", "review_scores_cleanliness", "bathrooms", "review_scores_value", "review_scores_location", "reviews_per_month"]]
Var_dep=df["host_identity_verified"]

X=Vars_Indep
y=Var_dep

#Dividir el conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

#Escalar los datos
escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)

#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión:")
print(matriz)
print("\n")

#Calcular la precisión
from sklearn.metrics import precision_score
precision1=precision_score(y_test, y_pred, average="binary", pos_label="t")
precision2=precision_score(y_test, y_pred, average="binary", pos_label="f")

#Calcular la exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)

#Calcular la sensibilidad
from sklearn.metrics import recall_score
sensibilidad1=recall_score(y_test, y_pred, average="binary", pos_label="t")
sensibilidad2=recall_score(y_test, y_pred, average="binary", pos_label="f")

print("Precision del modelo t:")
print(precision1)
print("Precision del modelo f:")
print(precision2)
print("\n")
print("Exactitud del modelo:")
print(exactitud)
print("\n")
print("Sensibilidad del modelo t:")
print(sensibilidad1)
print("Sensibilidad del modelo f:")
print(sensibilidad2)

Matriz de confusión:
[[   0 1829]
 [   0 9523]]


Precision del modelo t:
0.8388830162085976
Precision del modelo f:
0.0


Exactitud del modelo:
0.8388830162085976


Sensibilidad del modelo t:
1.0
Sensibilidad del modelo f:
0.0


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


### has_availability

In [28]:
Vars_Indep=df[["price", "beds", "review_scores_cleanliness", "bathrooms", "review_scores_value", "review_scores_location", "reviews_per_month"]]
Var_dep=df["has_availability"]

X=Vars_Indep
y=Var_dep

#Dividir el conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

#Escalar los datos
escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)

#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión:")
print(matriz)
print("\n")

#Calcular la precisión
from sklearn.metrics import precision_score
precision1=precision_score(y_test, y_pred, average="binary", pos_label="t")
precision2=precision_score(y_test, y_pred, average="binary", pos_label="f")

#Calcular la exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)

#Calcular la sensibilidad
from sklearn.metrics import recall_score
sensibilidad1=recall_score(y_test, y_pred, average="binary", pos_label="t")
sensibilidad2=recall_score(y_test, y_pred, average="binary", pos_label="f")

print("Precision del modelo t:")
print(precision1)
print("Precision del modelo f:")
print(precision2)
print("\n")
print("Exactitud del modelo:")
print(exactitud)
print("\n")
print("Sensibilidad del modelo t:")
print(sensibilidad1)
print("Sensibilidad del modelo f:")
print(sensibilidad2)

Matriz de confusión:
[[11352]]


Precision del modelo t:
1.0
Precision del modelo f:
0.0


Exactitud del modelo:
1.0


Sensibilidad del modelo t:
1.0
Sensibilidad del modelo f:
0.0


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:407: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


### instant_bookable

In [29]:
Vars_Indep=df[["price", "beds", "review_scores_cleanliness", "bathrooms", "review_scores_value", "review_scores_location", "reviews_per_month"]]
Var_dep=df["instant_bookable"]

X=Vars_Indep
y=Var_dep

#Dividir el conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

#Escalar los datos
escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)

#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión:")
print(matriz)
print("\n")

#Calcular la precisión
from sklearn.metrics import precision_score
precision1=precision_score(y_test, y_pred, average="binary", pos_label="t")
precision2=precision_score(y_test, y_pred, average="binary", pos_label="f")

#Calcular la exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)

#Calcular la sensibilidad
from sklearn.metrics import recall_score
sensibilidad1=recall_score(y_test, y_pred, average="binary", pos_label="t")
sensibilidad2=recall_score(y_test, y_pred, average="binary", pos_label="f")

print("Precision del modelo t:")
print(precision1)
print("Precision del modelo f:")
print(precision2)
print("\n")
print("Exactitud del modelo:")
print(exactitud)
print("\n")
print("Sensibilidad del modelo t:")
print(sensibilidad1)
print("Sensibilidad del modelo f:")
print(sensibilidad2)

Matriz de confusión:
[[8799    1]
 [2550    2]]


Precision del modelo t:
0.6666666666666666
Precision del modelo f:
0.7753106000528681


Exactitud del modelo:
0.7752818886539817


Sensibilidad del modelo t:
0.0007836990595611285
Sensibilidad del modelo f:
0.9998863636363636


### host_response_time

In [30]:
#Verificar los valores sin repetirse de una columna
unico=np.unique(df["host_response_time"])
unico

#CONVERTIR UNA VARIABLE CATEGÓRICA A DICOTÓMICA

df["host_response_time"]=df["host_response_time"].replace(["Sin registro", "a few days or more", "within a day","within a few hours"], "More than an hour")

In [31]:
Vars_Indep=df[["price", "beds", "review_scores_cleanliness", "bathrooms", "review_scores_value", "review_scores_location", "reviews_per_month"]]
Var_dep=df["host_response_time"]

X=Vars_Indep
y=Var_dep

#Dividir el conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

#Escalar los datos
escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)

#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión:")
print(matriz)
print("\n")

#Calcular la precisión
from sklearn.metrics import precision_score
precision1=precision_score(y_test, y_pred, average="binary", pos_label="within an hour")
precision2=precision_score(y_test, y_pred, average="binary", pos_label="More than an hour")

#Calcular la exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)

#Calcular la sensibilidad
from sklearn.metrics import recall_score
sensibilidad1=recall_score(y_test, y_pred, average="binary", pos_label="within an hour")
sensibilidad2=recall_score(y_test, y_pred, average="binary", pos_label="More than an hour")

print("Precision del modelo within an hour:")
print(precision1)
print("Precision del modelo More than an hour:")
print(precision2)
print("\n")
print("Exactitud del modelo:")
print(exactitud)
print("\n")
print("Sensibilidad del modelo within an hour:")
print(sensibilidad1)
print("Sensibilidad del modelo More than an hour:")
print(sensibilidad2)

Matriz de confusión:
[[1939 3153]
 [1512 4748]]


Precision del modelo within an hour:
0.6009365903050247
Precision del modelo More than an hour:
0.5618661257606491


Exactitud del modelo:
0.5890591966173362


Sensibilidad del modelo within an hour:
0.7584664536741214
Sensibilidad del modelo More than an hour:
0.3807934014139827


### room_type

In [32]:
#Verificar los valores sin repetirse de una columna
unico=np.unique(df["room_type"])
unico

#CONVERTIR UNA VARIABLE CATEGÓRICA A DICOTÓMICA

df["room_type"]=df["room_type"].replace(["Hotel room", "Private room", "Shared room"], "Otro")

In [33]:
Vars_Indep=df[["price", "beds", "review_scores_cleanliness", "bathrooms", "review_scores_value", "review_scores_location", "reviews_per_month"]]
Var_dep=df["room_type"]

X=Vars_Indep
y=Var_dep

#Dividir el conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

#Escalar los datos
escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)


#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión:")
print(matriz)
print("\n")

#Calcular la precisión
from sklearn.metrics import precision_score
precision1=precision_score(y_test, y_pred, average="binary", pos_label="Entire home/apt")
precision2=precision_score(y_test, y_pred, average="binary", pos_label="Otro")

#Calcular la exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)

#Calcular la sensibilidad
from sklearn.metrics import recall_score
sensibilidad1=recall_score(y_test, y_pred, average="binary", pos_label="Entire home/apt")
sensibilidad2=recall_score(y_test, y_pred, average="binary", pos_label="Otro")

print("Precision del modelo Entire home/apt:")
print(precision1)
print("Precision del modelo Otro:")
print(precision2)
print("\n")
print("Exactitud del modelo:")
print(exactitud)
print("\n")
print("Sensibilidad del modelo Entire home/apt:")
print(sensibilidad1)
print("Sensibilidad del modelo Otro:")
print(sensibilidad2)



Matriz de confusión:
[[8844  197]
 [1894  417]]


Precision del modelo Entire home/apt:
0.8236170609051965
Precision del modelo Otro:
0.6791530944625407


Exactitud del modelo:
0.8158033826638478


Sensibilidad del modelo Entire home/apt:
0.9782103749585223
Sensibilidad del modelo Otro:
0.18044136737343142


### availability_365

In [34]:
#Crear categorias a partir de clases
Max=df["availability_365"].max()
Min=df["availability_365"].min()


limites=[Min, Max]
limites

[np.int64(0), np.int64(365)]

In [35]:
#Declarar dos intervalos
intervalos=np.linspace(-0.1,365.1, 3)
intervalos

categorias=["Disponibilidad menor a medio año", "Disponibilidad mayor a medio año"]

df["availability_365"]=pd.cut(x=df["availability_365"], bins=intervalos, labels=categorias)


In [36]:
Vars_Indep=df[["price", "beds", "review_scores_cleanliness", "bathrooms", "review_scores_value", "review_scores_location", "reviews_per_month"]]
Var_dep=df["availability_365"]

X=Vars_Indep
y=Var_dep

#Dividir el conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

#Escalar los datos
escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)

#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión:")
print(matriz)
print("\n")

#Calcular la precisión
from sklearn.metrics import precision_score
precision1=precision_score(y_test, y_pred, average="binary", pos_label="Disponibilidad menor a medio año")
precision2=precision_score(y_test, y_pred, average="binary", pos_label="Disponibilidad mayor a medio año")

#Calcular la exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)

#Calcular la sensibilidad
from sklearn.metrics import recall_score
sensibilidad1=recall_score(y_test, y_pred, average="binary", pos_label="Disponibilidad menor a medio año")
sensibilidad2=recall_score(y_test, y_pred, average="binary", pos_label="Disponibilidad mayor a medio año")

print("Precision del modelo Disponibilidad menor a medio año:")
print(precision1)
print("Precision del modelo Disponibilidad mayor a medio año:")
print(precision2)
print("\n")
print("Exactitud del modelo:")
print(exactitud)
print("\n")
print("Sensibilidad del modelo Disponibilidad menor a medio año:")
print(sensibilidad1)
print("Sensibilidad del modelo Disponibilidad mayor a medio año:")
print(sensibilidad2)



Matriz de confusión:
[[2067 3265]
 [1682 4338]]


Precision del modelo Disponibilidad menor a medio año:
0.570564250953571
Precision del modelo Disponibilidad mayor a medio año:
0.5513470258735663


Exactitud del modelo:
0.5642177589852009


Sensibilidad del modelo Disponibilidad menor a medio año:
0.7205980066445182
Sensibilidad del modelo Disponibilidad mayor a medio año:
0.3876594148537134


### availability_30

In [37]:
#Crear categorias a partir de clases
Max=df["availability_30"].max()
Min=df["availability_30"].min()


limites=[Min, Max]
limites

[np.int64(0), np.int64(30)]

In [38]:
#Declarar dos intervalos
intervalos=np.linspace(-0.1,30.1, 3)
intervalos

categorias=["Poca disponibilidad en el siguiente mes", "Mucha disponibilidad en el siguiente mes"]

df["availability_30"]=pd.cut(x=df["availability_30"], bins=intervalos, labels=categorias)

In [39]:
Vars_Indep=df[["price", "beds", "review_scores_cleanliness", "bathrooms", "review_scores_value", "review_scores_location", "reviews_per_month"]]
Var_dep=df["availability_30"]

X=Vars_Indep
y=Var_dep

#Dividir el conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

#Escalar los datos
escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)

#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión:")
print(matriz)
print("\n")

#Calcular la precisión
from sklearn.metrics import precision_score
precision1=precision_score(y_test, y_pred, average="binary", pos_label="Mucha disponibilidad en el siguiente mes")
precision2=precision_score(y_test, y_pred, average="binary", pos_label="Poca disponibilidad en el siguiente mes")

#Calcular la exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)

#Calcular la sensibilidad
from sklearn.metrics import recall_score
sensibilidad1=recall_score(y_test, y_pred, average="binary", pos_label="Mucha disponibilidad en el siguiente mes")
sensibilidad2=recall_score(y_test, y_pred, average="binary", pos_label="Poca disponibilidad en el siguiente mes")

print("Precision del modelo Mucha disponibilidad en el siguiente mes:")
print(precision1)
print("Precision del modelo Poca disponibilidad en el siguiente mes:")
print(precision2)
print("\n")
print("Exactitud del modelo:")
print(exactitud)
print("\n")
print("Sensibilidad del modelo Mucha disponibilidad en el siguiente mes:")
print(sensibilidad1)
print("Sensibilidad del modelo Poca disponibilidad en el siguiente mes:")
print(sensibilidad2)

Matriz de confusión:
[[3107 2473]
 [2280 3492]]


Precision del modelo Mucha disponibilidad en el siguiente mes:
0.5767588639316874
Precision del modelo Poca disponibilidad en el siguiente mes:
0.5854149203688181


Exactitud del modelo:
0.58130725863284


Sensibilidad del modelo Mucha disponibilidad en el siguiente mes:
0.5568100358422939
Sensibilidad del modelo Poca disponibilidad en el siguiente mes:
0.604989604989605


### review_scores_rating

In [40]:
#Crear categorias a partir de clases
Max=df["review_scores_rating"].max()
Min=df["review_scores_rating"].min()


limites=[Min, Max]
limites

[np.float64(4.5), np.float64(5.0)]

In [41]:
#Declarar dos intervalos
intervalos=np.linspace(4.49,5.1, 3)
intervalos

categorias=["Rating de calificación medio", "Rating de calificación alto"]

df["review_scores_rating"]=pd.cut(x=df["review_scores_rating"], bins=intervalos, labels=categorias)

In [42]:
Vars_Indep=df[["price", "beds", "review_scores_cleanliness", "bathrooms", "review_scores_value", "review_scores_location", "reviews_per_month"]]
Var_dep=df["review_scores_rating"]

X=Vars_Indep
y=Var_dep

#Dividir el conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

#Escalar los datos
escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)

#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión:")
print(matriz)
print("\n")

#Calcular la precisión
from sklearn.metrics import precision_score
precision1=precision_score(y_test, y_pred, average="binary", pos_label="Rating de calificación alto")
precision2=precision_score(y_test, y_pred, average="binary", pos_label="Rating de calificación medio")

#Calcular la exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)

#Calcular la sensibilidad
from sklearn.metrics import recall_score
sensibilidad1=recall_score(y_test, y_pred, average="binary", pos_label="Rating de calificación alto")
sensibilidad2=recall_score(y_test, y_pred, average="binary", pos_label="Rating de calificación medio")

print("Precision del modelo Rating de calificación alto:")
print(precision1)
print("Precision del modelo Rating de calificación medio:")
print(precision2)
print("\n")
print("Exactitud del modelo:")
print(exactitud)
print("\n")
print("Sensibilidad del modelo Rating de calificación alto:")
print(sensibilidad1)
print("Sensibilidad del modelo Rating de calificación medio:")
print(sensibilidad2)

Matriz de confusión:
[[9404  227]
 [1292  429]]


Precision del modelo Rating de calificación alto:
0.8792071802543007
Precision del modelo Rating de calificación medio:
0.6539634146341463


Exactitud del modelo:
0.8661909795630726


Sensibilidad del modelo Rating de calificación alto:
0.9764302772297788
Sensibilidad del modelo Rating de calificación medio:
0.2492736780941313


### number_of_reviews

In [43]:
#Crear categorias a partir de clases
Max=df["number_of_reviews"].max()
Min=df["number_of_reviews"].min()


limites=[Min, Max]
limites

[np.float64(0.0), np.float64(62.0)]

In [44]:
#Declarar dos intervalos
intervalos=np.linspace(-0.1,62.1, 3)
intervalos

categorias=["Pocas calificaciones", "Muchas calificaciones"]

df["number_of_reviews"]=pd.cut(x=df["number_of_reviews"], bins=intervalos, labels=categorias)

In [45]:
Vars_Indep=df[["price", "beds", "review_scores_cleanliness", "bathrooms", "review_scores_value", "review_scores_location", "reviews_per_month"]]
Var_dep=df["number_of_reviews"]

X=Vars_Indep
y=Var_dep

#Dividir el conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

#Escalar los datos
escalar= StandardScaler()

X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)

#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión:")
print(matriz)
print("\n")

#Calcular la precisión
from sklearn.metrics import precision_score
precision1=precision_score(y_test, y_pred, average="binary", pos_label="Muchas calificaciones")
precision2=precision_score(y_test, y_pred, average="binary", pos_label="Pocas calificaciones")

#Calcular la exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)

#Calcular la sensibilidad
from sklearn.metrics import recall_score
sensibilidad1=recall_score(y_test, y_pred, average="binary", pos_label="Muchas calificaciones")
sensibilidad2=recall_score(y_test, y_pred, average="binary", pos_label="Pocas calificaciones")

print("Precision del modelo Muchas calificaciones:")
print(precision1)
print("Precision del modelo Pocas calificaciones:")
print(precision2)
print("\n")
print("Exactitud del modelo:")
print(exactitud)
print("\n")
print("Sensibilidad del modelo Muchas calificaciones:")
print(sensibilidad1)
print("Sensibilidad del modelo Pocas calificaciones:")
print(sensibilidad2)

Matriz de confusión:
[[    0  1177]
 [    0 10175]]


Precision del modelo Muchas calificaciones:
0.0
Precision del modelo Pocas calificaciones:
0.8963178294573644


Exactitud del modelo:
0.8963178294573644


Sensibilidad del modelo Muchas calificaciones:
0.0
Sensibilidad del modelo Pocas calificaciones:
1.0


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
